### ISSUE TITLE
Make website more responsive

### ISSUE THREAD

**Issue by Omoorion** [Ido-Barnea/Chess-But-Better#266]
- [ ] Board should resize along with the screen zoom.
- [ ] Board should not have `position: absolute`.
- [ ] Board notation numbers should not cover the board pawns when zooming in but stay relative to them.
- [ ] Deal with board select buttons not resizing along with the screen zoom and text being cut short on zoom.
- [ ] Deal with left-column elements covering each other when zooming in.
- [ ] Make inventory squares resize along with the screen zoom.

**Comment by Ido-Barnea** [comment]
Issue is too general. Please open an issue for each point. @Omoorion
