### ISSUE TITLE
Add `fill="currentColor"` property to all item svgs

### ISSUE THREAD

**Issue by Omoorion** [Ido-Barnea/Chess-But-Better#274]
### Requested Changes
- [ ] Add `fill="currentColor"` property to all item svgs.

**Comment by Ido-Barnea** [comment]
@Omoorion Please add the following information to the issue description:
1. What is `currentColor`?
2. What will adding `currentColor` to each SVG do? What are the benefits? What does this issue fix/improve?

**Comment by Omoorion** [comment]
`currentColor` picks the text color from the parent and applies it to the svg's color, pretty minor really, just adds consistency to the code

**Comment by Ido-Barnea** [comment]
> `currentColor` picks the text color from the parent and applies it to the svg's color, pretty minor really, just adds consistency to the code

Good to know, please add this information to the issue description.

**Comment by Ido-Barnea** [comment]
Closing stale issue
