### ISSUE TITLE
Pieces element does not dissapear when dragged off the hell board to void

### ISSUE THREAD

**Issue by Monkey-bored** [Ido-Barnea/Chess-But-Better#275]
### Describe the bug
The piece element does not disappear after dragging it off the hell board to the void

### Steps To Reproduce
1. Get any piece to hell
2. drag it off the board

### Expected behavior
The element of the piece should disappear

**Comment by Ido-Barnea** [comment]
Update: the same bug occurs in the `HELL` board @Monkey-bored.

**Comment by Monkey-bored** [comment]
> Update: the same bug occurs in the `HELL` board @Monkey-bored.

You mean the `HEAVEN` board?

**Comment by Ido-Barnea** [comment]
Yes, my bad
