### ISSUE TITLE
Fix not being able to eat pieces sometimes on Firefox

### ISSUE THREAD

**Issue by Ido-Barnea** [Ido-Barnea/Chess-But-Better#5]
For some reason, sometimes, when trying to eat a piece, the following error occurs:

> Uncaught TypeError: _targetCoordinates is null
	isValidMove file:///home/omoor/Downloads/Chess-But-Better-main/app.js:232
    onDragDrop file:///home/omoor/Downloads/Chess-But-Better-main/app.js:158

The error seems to only occur on Firefox.

To reproduce:
1. white P moved from (3,6) to (3,4).
2. black p moved from (4,1) to (4,3).
3. black p was killed by white P. -> error occurs here.

**Comment by zargad** [comment]
The issue is that eating on a cross from a piece will almost always fail.

**Comment by Omoorion** [comment]
Issue fixed itself, no longer reproduceble on firefox.
probably works because we moved to typescript or smthn idk
