### ISSUE TITLE
Can drag any piece off the board despite the move being illegal

### ISSUE THREAD

**Issue by Omoorion** [Ido-Barnea/Chess-But-Better#50]
ISSUE DISCOVERED BY NAHUM WHO CAN FINALLY TEST
for example:
you can drag a chess pawn off the board by dragging him to the right/left no matter the distance from the edge of the board...

**Comment by Ido-Barnea** [comment]
Not an issue. This is how the logic should work. Please ask me before opening an issue if you are not sure @Omoorion .

**Comment by Monkey-bored** [comment]
How is it not an issue????
