### ISSUE TITLE
Dragging pieces doesn't work sometimes

### ISSUE THREAD

**Issue by Omoorion** [Ido-Barnea/Chess-But-Better#51]
How to reproduce:
1. Position White Queen at a2.
2. Position White King at a1.

**Comment by Omoorion** [comment]
the black pieces are irrelevant to the issue, it is an issue that origins from that certain position/notations on the board

**Comment by Ido-Barnea** [comment]
@Omoorion OK. That was not clear. If you could add a step in between saying to move black but that it doesn't matter I think that would clarify the steps to reproduce the bug.

**Comment by Ido-Barnea** [comment]
Couldn't reproduce
