### ISSUE TITLE
Hit box getting bigger

### ISSUE THREAD

**Issue by gitorator** [Ido-Barnea/Chess-But-Better#58]
Steps to reproduce:
1. Place any piece anywhere and see that the hit box of the square is augmenting a bit.

Reference picture:
![Screenshot 2023-10-17 234537](https://github.com/Ido-Barnea/Chess-But-Better/assets/148235898/f2c304d4-7f97-4b6a-b5ef-20f1a1a8eda4)

**Comment by Ido-Barnea** [comment]
It was actually the pieces that took more space than they should have been taking. Fixed now but please make sure the facts you write in the issue are facts.
